import React, { useState } from 'react';
import './QuizScreen.css';

// ─── Sample questions built from your real content.js word shape ──────────────
// These are fallback questions used when no `questions` prop is passed in.
// In normal use, pass questions generated by generateQuiz() from utils/claude.js
// e.g. const { questions } = await generateQuiz(lessonWords);
const SAMPLE_QUESTIONS = [
  {
    id: 1,
    prompt: 'What does this mean?',
    word: 'बाबा (Baba)',
    options: ['Father / Elder', 'Brother', 'Uncle', 'Friend'],
    correct: 0,
    explanation: 'Baba = father or a respected elder. In Bhojpuri, it\'s used affectionately for one\'s father.',
    explanationHindi: 'बाबा = पिता या सम्मानित बुजुर्ग।',
  },
  {
    id: 2,
    prompt: 'How do you say "water" in Bhojpuri?',
    word: 'Water / पानी',
    options: ['पनिया', 'रोटी', 'दूध', 'चाय'],
    correct: 0,
    explanation: '"Paniya" is the Bhojpuri word for water. Close to Hindi "paani".',
    explanationHindi: '"पनिया" भोजपुरी में पानी के लिए उपयोग होता है।',
  },
  {
    id: 3,
    prompt: 'What does this mean?',
    word: 'काम (Kaam)',
    options: ['Work / Task', 'Play', 'Sleep', 'Eat'],
    correct: 0,
    explanation: '"Kaam" means work or task — same as in Hindi.',
    explanationHindi: '"काम" का अर्थ है कार्य या काम।',
  },
];

// ─── Helper: convert the word shape from content.js / generateQuiz() ──────────
// generateQuiz() returns: { hindi, roman, meaning, options, correct }
// This screen expects: { id, prompt, word, options, correct, explanation, explanationHindi }
// Call this if you're passing raw quiz output from generateQuiz():
//   const questions = convertQuizQuestions(rawQuiz.questions);
export function convertQuizQuestions(rawQuestions) {
  return rawQuestions.map((q, i) => ({
    id: i + 1,
    prompt: 'What does this mean?',
    word: `${q.hindi} (${q.roman})`,
    options: q.options,
    correct: q.correct,
    explanation: `"${q.roman}" means "${q.meaning}".`,
    explanationHindi: `${q.hindi} = ${q.meaning}`,
  }));
}
// ─────────────────────────────────────────────────────────────────────────────

const OPTION_LETTERS = ['A', 'B', 'C', 'D'];

export default function QuizScreen({ questions = SAMPLE_QUESTIONS, totalLives = 3, onFinish, onBack }) {
  const [current, setCurrent]   = useState(0);
  const [selected, setSelected] = useState(null);
  const [lives, setLives]       = useState(totalLives);
  const [correct, setCorrect]   = useState(0);
  const [finished, setFinished] = useState(false);

  const q          = questions[current];
  const isAnswered = selected !== null;
  const isCorrect  = selected === q?.correct;
  const progress   = (current / questions.length) * 100;

  function handleSelect(idx) {
    if (isAnswered) return;
    setSelected(idx);
    if (idx !== q.correct) setLives(l => Math.max(0, l - 1));
    else setCorrect(c => c + 1);
  }

  function handleNext() {
    if (current + 1 >= questions.length) {
      setFinished(true);
    } else {
      setCurrent(c => c + 1);
      setSelected(null);
    }
  }

  function handleRetry() {
    setCurrent(0);
    setSelected(null);
    setCorrect(0);
    setLives(totalLives);
    setFinished(false);
  }

  // ── Finished screen ──────────────────────────────────────────────────────
  if (finished) {
    const pct       = Math.round((correct / questions.length) * 100);
    const isPerfect = correct === questions.length;
    return (
      <div className="bl-quiz">
        <div className="bl-quiz-result">
          <div className="bl-result-emoji">{isPerfect ? '🏆' : pct >= 60 ? '🌟' : '💪'}</div>
          <h2 className="bl-result-title">
            {isPerfect ? 'Ekdum perfect!' : pct >= 60 ? 'Bahut accha!' : 'Keep practicing!'}
          </h2>
          <p className="bl-result-sub">
            {correct} of {questions.length} correct · {pct}%
          </p>
          <div className="bl-result-stats">
            <div className="bl-result-stat">
              <span className="bl-result-stat-val">{correct}</span>
              <span className="bl-result-stat-label">Correct</span>
            </div>
            <div className="bl-result-stat">
              <span className="bl-result-stat-val">{questions.length - correct}</span>
              <span className="bl-result-stat-label">Wrong</span>
            </div>
            <div className="bl-result-stat">
              <span className="bl-result-stat-val">{lives}</span>
              <span className="bl-result-stat-label">Lives left</span>
            </div>
          </div>
          <button className="bl-result-btn bl-result-btn--primary" onClick={onFinish}>
            Continue →
          </button>
          <button className="bl-result-btn bl-result-btn--secondary" onClick={handleRetry}>
            Retry
          </button>
        </div>
      </div>
    );
  }

  // ── Quiz screen ──────────────────────────────────────────────────────────
  return (
    <div className="bl-quiz">
      {/* ── Top bar ── */}
      <div className="bl-quiz-topbar">
        <button className="bl-quiz-back" onClick={onBack} aria-label="Go back">✕</button>
        <div className="bl-quiz-progress-wrap">
          <div className="bl-quiz-progress-fill" style={{ width: `${progress}%` }} />
        </div>
        <div className="bl-quiz-lives" aria-label={`${lives} lives remaining`}>
          {Array.from({ length: totalLives }, (_, i) => (
            <span key={i} className={`bl-heart ${i < lives ? 'bl-heart--full' : 'bl-heart--empty'}`}>♥</span>
          ))}
        </div>
      </div>

      {/* ── Question ── */}
      <div className="bl-quiz-body">
        <p className="bl-quiz-counter">{current + 1} of {questions.length}</p>
        <p className="bl-quiz-prompt">{q.prompt}</p>
        <div className="bl-quiz-word">{q.word}</div>

        {/* ── Options ── */}
        <div className="bl-quiz-options">
          {q.options.map((opt, idx) => {
            let state = '';
            if (isAnswered) {
              if (idx === q.correct)  state = 'correct';
              else if (idx === selected) state = 'wrong';
            }
            return (
              <button
                key={idx}
                className={`bl-option bl-option--${state || 'idle'}`}
                onClick={() => handleSelect(idx)}
                disabled={isAnswered}
              >
                <span className="bl-option-letter">
                  {isAnswered && idx === q.correct ? '✓'
                    : isAnswered && idx === selected ? '✕'
                    : OPTION_LETTERS[idx]}
                </span>
                <span className="bl-option-text">{opt}</span>
              </button>
            );
          })}
        </div>
      </div>

      {/* ── Feedback bar (shown after answering) ── */}
      {isAnswered && (
        <div className={`bl-feedback bl-feedback--${isCorrect ? 'correct' : 'wrong'}`}>
          <div className="bl-feedback-inner">
            <div className="bl-feedback-icon">{isCorrect ? '✓' : '✕'}</div>
            <div className="bl-feedback-content">
              <p className="bl-feedback-title">
                {isCorrect ? 'Bilkul sahi! 🎉' : 'Galat jawab 😅'}
              </p>
              <p className="bl-feedback-explain">{q.explanation}</p>
              <p className="bl-feedback-hindi">{q.explanationHindi}</p>
            </div>
          </div>
          <button className="bl-continue-btn" onClick={handleNext}>
            {current + 1 >= questions.length ? 'Finish' : 'Continue'} →
          </button>
        </div>
      )}
    </div>
  );
}